return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      auto_install = true,
      -- ensure_installed = {
      --   "bash",
      --   "c",
      --   "html",
      --   "css",
      --   "json",
      --   "lua",
      --   "markdown",
      --   "python",
      --   "query",
      --   "regex",
      --   "typescript",
      --   "vim",
      --   "yaml",
      --   "rust",
      --   "bash",
      --   "toml",
      --   "rust",
      --   "fish",
      --   "kdl",
      --   "vimdoc",
      --   "markdown_inline",
      -- },
    },
  },
}
